image: registry.gitlab.com/kodality/gitlab-builders/ng

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
      - node_modules

stages:
  - build
  - release


build:
  stage: build
  extends: .dependencies_cache
  before_script:
    - echo "@kodality-web:registry=https://kexus.kodality.com/repository/npm/" >> ~/.npmrc
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - "**/dist"
    expire_in: 1 hour
  only:
    - branches
    - tags


release latest:
  stage: release
  image: docker:latest
  before_script:
    - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com
    - docker buildx create --name mybuilder --bootstrap --use
  script:
    - export BUILD_TIME=$(date +%s)
    - docker buildx build --platform linux/amd64,linux/arm64 -t docker.kodality.com/termx-fml-editor:latest --build-arg BUILD_TIME=$BUILD_TIME --push .
  only:
    - main

release tag:
  stage: release
  image: docker:latest
  before_script:
    - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com
    - docker buildx create --name mybuilder --bootstrap --use
  script:
    - export APP_VERSION="$CI_COMMIT_REF_NAME"
    - export BUILD_TIME=$(date +%s)
    - docker buildx build --platform linux/amd64,linux/arm64 -t docker.kodality.com/termx-fml-editor:$APP_VERSION --build-arg BUILD_TIME=$BUILD_TIME --push .
  only:
    - /^\d*\.\d*\.\d*$/
  except:
    - branches
