image: registry.gitlab.com/kodality/gitlab-builders/ng

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
      - node_modules

stages:
  - build
  - release

build:
  stage: build
  extends: .dependencies_cache
  before_script:
    - echo "@kodality-web:registry=https://kexus.kodality.com/repository/npm/" >> ~/.npmrc
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - "**/dist"
    expire_in: 1 hour
  only:
    - branches
    - tags

publish:
  stage: release
  image: docker:stable
  before_script:
    - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com
  script:
    - export BUILD_TIME=$(date +%s)
    - docker build -t docker.kodality.com/termx-fml-editor:latest --build-arg BUILD_TIME=$BUILD_TIME .
    - docker push docker.kodality.com/termx-fml-editor:latest
  only:
    - master
